builds:
  -
    binary: fabio
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - freebsd
      - netbsd
      - openbsd
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: arm64

archives:
  - id: bin
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Env.GOVERSION }}-{{ .Os }}_{{ .Arch }}'
    format: binary

checksum:
  name_template: '{{.ProjectName}}-{{.Version}}-{{ .Env.GOVERSION }}.sha256'

signs:
  -
    artifacts: checksum

dockers:
  -
    dockerfile: Dockerfile-goreleaser
    image_templates:
      - 'fabiolb/fabio:latest'
      - 'fabiolb/fabio:{{ .Version }}-{{ .Env.GOVERSION }}'
    extra_files:
      - fabio.properties
