FROM alpine:latest AS build

ARG hugo_version=0.62.2

## fetch and install hugo
RUN wget -q -O - \
    https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_${hugo_version}_Linux-64bit.tar.gz \
    | tar -zxf - hugo && \
    mv hugo /usr/local/bin/hugo && \
    chmod 0755 /usr/local/bin/hugo

## generate static content
COPY docs /opt/docs
WORKDIR /opt/docs
RUN /usr/local/bin/hugo --buildDrafts --cleanDestinationDir --destination /opt/output

FROM alpine:latest

## install thttpd (http://acme.com/software/thttpd/)
RUN apk add --no-cache thttpd

## copy static assets form build
COPY --from=build /opt/output /var/www/http

## use package user
USER thttpd

EXPOSE 1180

## launch thttpd to serve static content
ENTRYPOINT ["/usr/sbin/thttpd"]
CMD ["-p", "1180", "-d", "/var/www/http", "-l", "/dev/stdout", "-D"]
