FROM ubuntu
COPY consul_1.0.6_linux_amd64.zip /tmp
COPY vault_0.9.6_linux_amd64.zip /tmp
COPY go1.10.2.linux-amd64.tar.gz /tmp
RUN apt-get update && apt-get -y install unzip make git-core
RUN unzip /tmp/consul*.zip -d /usr/local/bin
RUN unzip /tmp/vault*.zip -d /usr/local/bin
RUN tar -C /usr/local -x -f /tmp/go*.tar.gz
ENV PATH=/usr/local/go/bin:/root/go/bin:$PATH
WORKDIR /root/go/src/github.com/fabiolb/fabio
COPY . .
CMD "/bin/bash"
