FROM ubuntu
RUN apt-get update && apt-get -y install unzip make git-core
ARG consul_version
ARG vault_version
ARG go_version
COPY consul_${consul_version}_linux_amd64.zip /tmp
COPY vault_${vault_version}_linux_amd64.zip /tmp
COPY go${go_version}.linux-amd64.tar.gz /tmp
RUN unzip /tmp/consul_${consul_version}_linux_amd64.zip -d /usr/local/bin
RUN unzip /tmp/vault_${vault_version}_linux_amd64.zip -d /usr/local/bin
RUN tar -C /usr/local -x -f /tmp/go${go_version}.linux-amd64.tar.gz
ENV PATH=/usr/local/go/bin:/root/go/bin:$PATH
WORKDIR /root/go/src/github.com/fabiolb/fabio
COPY . .
CMD "/bin/bash"
