FROM ubuntu
RUN apt-get update && apt-get -y install make git-core unzip
ARG consul_version=1.0.6
ARG vault_version=0.9.6
ARG go_version=1.10.3
ADD https://releases.hashicorp.com/consul/${consul_version}/consul_${consul_version}_linux_amd64.zip /usr/local/bin
ADD https://releases.hashicorp.com/vault/${vault_version}/vault_${vault_version}_linux_amd64.zip /usr/local/bin
ADD https://dl.google.com/go/go${go_version}.linux-amd64.tar.gz /usr/local
RUN cd /usr/local/bin && unzip consul_${consul_version}_linux_amd64.zip
RUN cd /usr/local/bin && unzip vault_${vault_version}_linux_amd64.zip
RUN cd /usr/local && tar xf go${go_version}.linux-amd64.tar.gz
ENV PATH=/usr/local/go/bin:/root/go/bin:$PATH
WORKDIR /root/go/src/github.com/fabiolb/fabio
COPY . .
CMD "/bin/bash"
